### ISSUE TITLE
(1.19.4) Blue Skies dungeon/boss track keys mistyped

### ISSUE THREAD

**Issue by KingPhygieBoo** [GizmoTheMoonPig/musicmanager#1]
Came across your project after seeing you mention you were adding Blue Skies integration, and wanted to check it out.

It works great for the ambient tracks, however I noticed the directory for the dungeon related tracks is typed as "dungeons" rather than "dungeon", preventing them from displaying in-game. As another note, those tracks also specify "Jon Lachney" instead of just "Lachney" like the others.

It's really awesome to see integration with Blue Skies, If you hadn't added it built-in, I'm sure we would've integrated with it ourselves!

**Comment by GizmoTheMoonPig** [comment]
Very glad you like it :)
i'll get the dungeon keys fixed. I dont know how I didnt notice the difference between how I specified the authors on those tracks. Would you rather all the tracks say "Jon Lachney" or just "Lachney"? Want to make sure they all match

**Comment by GizmoTheMoonPig** [comment]
tested just to make sure, looks like everything works correctly now. I'll push out a new build as soon as address one other thing. Thanks for letting me know about this :)
