### ISSUE TITLE
Compatibility with Supplementaries

### ISSUE THREAD

**Issue by QwertRvg** [GizmoTheMoonPig/musicmanager#10]
The Supplementaries let's you play the Pancake item as a little secret music disc. It starts with some glitchiness but does turn into an actual song.
The music toast in that moment is simply the internal name "block.supplementaries...". Having the actual song name show up would be great.
(If their isn't a proper name then at least something like "Pancake".

**Comment by GizmoTheMoonPig** [comment]
weird its not supported by default... I'll take a look into it. Thanks for letting me know!

**Comment by QwertRvg** [comment]
thanks so much!
hope it works

**Comment by GizmoTheMoonPig** [comment]
Sorry this took so long, it'll be fixed once [this Pull Request](https://github.com/MehVahdJukaar/Supplementaries/pull/939) is merged. Nothing else I can really do on my end, shouldnt be up to this mod to fix other mod's lang keys lol

**Comment by QwertRvg** [comment]
that's great, thanks so much!
