### ISSUE TITLE
Backporting features to stale versions

### ISSUE THREAD

**Issue by Jonathing** [GizmoTheMoonPig/musicmanager#13]
I admit this is rather selfish on my part, but I am interested in having the 1.19.2 and 1.19.4 versions of this mod getting the features added in the 1.20.1 version, *especially* the biome overrides. I am more than happy to make PRs myself that backport the current version to these stale versions of then game, but I thought I'd make this issue and ask you first if you were already going to plan on doing that.

**Comment by GizmoTheMoonPig** [comment]
Sure, I don't mind backporting everything real fast with how small this mod is. I've been meaning to do a release for 1.18 too so I'll get that done real fast today too

**Comment by Jonathing** [comment]
Thanks man, I appreciate it.

**Comment by Jonathing** [comment]
Closed by 1e2f3a286456f6db3e1944ef749b04d6ed155ecf and cebb9c9c186047abeabdea6886da866051285979. Thanks so much, man!
