### ISSUE TITLE
After latest update, Music Manager fails to load

### ISSUE THREAD

**Issue by VillainVibe** [GizmoTheMoonPig/musicmanager#14]
Asking for minecraft 1.19.4 using 1.20.1

Seems like you taged the wrong version on curseforge

**Comment by GizmoTheMoonPig** [comment]
which version of music manager are you using? Everything looks properly tagged...
I did initially tag the 1.19.4 file incorrectly but that should've been fixed like 2 hours ago, I caught it before they were approved

**Comment by Krimatoria** [comment]
> какую версию музыкального менеджера вы используете? Все выглядит правильно помеченным... Изначально я неправильно пометил файл 1.19.4, но это должно было быть исправлено примерно 2 часа назад, я заметил это до того, как они были одобрены.

It's still like this) I also faced this problem
![image](https://github.com/GizmoTheMoonPig/musicmanager/assets/106809386/28938ba6-d774-4660-aaf0-96852cb6bf7f)

**Comment by GizmoTheMoonPig** [comment]
alright, I have absolutely zero idea why the CF app still shows it tagged like that, but it's not. I'm just gonna delete and reupload that version in hope that that'll fix it

**Comment by Krimatoria** [comment]
> alright, I have absolutely zero idea why the CF app still shows it tagged like that, but it's not. I'm just gonna delete and reupload that version in hope that that'll fix it

Waiting for the download)
![image](https://github.com/GizmoTheMoonPig/musicmanager/assets/106809386/5d089266-c3bc-4420-8404-87ab535ec944)
