### ISSUE TITLE
[Mod compatibility suggestion] medievalmusic

### ISSUE THREAD

**Issue by gaussandhisgun** [GizmoTheMoonPig/musicmanager#4]
> If there are any other mods that either add music tracks to the overworld or have their own dimension with custom music tracks, please let me know and I will add support for them! 

Well then. [medievalmusic](https://legacy.curseforge.com/minecraft/mc-mods/medieval-music) does exactly that, but right now its tracks are recognized as builtins.

**Comment by GizmoTheMoonPig** [comment]
I looked into this and quickly learned that this mod is just replacing the vanilla game soundtrack with their stuff. Unfortunately, this means I can't support this as its not adding its own tracks to the game.
